### ISSUE TITLE
Modern Greek gap analysis

### ISSUE THREAD

**Issue by svgeesus** [w3c/typography#62]
The document currently titled [Greek Gap Analysis](https://w3c.github.io/eurlreq/gap-analysis/grek-gap) should probably be retitled Modern Greek Gap Analysis, for clarity. In other words it does not cover recent historical Polytonic Greek, nor Coptic Greek as used in the Orthodox Church, nor Ancient or Archaic Greek.

Otherwise, the gaps would be quite different (and rather more severe).

**Comment by himorin** [comment]
seems better to be filed against to https://github.com/w3c/eurlreq?

**Comment by r12a** [comment]
@svgeesus before i close this issue and move it to eurlreq repo, was there a particular link that led you here (rather than to eurlreq) that i should change?

**Comment by r12a** [comment]
Ah, i think i found it. The one in the big green box at the start, which i forgot to remove.

**Comment by r12a** [comment]
Ok, done.  So i'll close this issue without moving it.  Thanks for pointing that out @svgeesus, it also applied to the Georgian, Dutch and Hungarian docs (which all used an old template).

**Comment by r12a** [comment]
Btw, thanks for pointing out that bug in the gap-analysis doc, @svgeesus. It has been fixed for the Greek, Georgian, Hungarian, and Dutch gap analysis docs, which is why this is now closed.

If there's a need for additional discussion, please feel free to raise a new issue at https://github.com/w3c/eurlreq/issues

**Comment by svgeesus** [comment]
Thanks, Richard! 

I'm aware of some people noodling slowly on an Ancient Greek gap analysis, so I thought it important to be clear here. I'm satisfied with the resolution.

**Comment by r12a** [comment]
Thanks also for suggesting the change of name for the Greek document. I felt it was appropriate, since our primary concern (at least initially) is to ensure the Web serves the needs of current users.  We can always create a new doc for Ancient Greek if there is a need and if we have some expertise to bring to bear.  But priorities-wise, modern users are currently highest in the frame.
