### ISSUE TITLE
Should text-decoration-skip apply to overline and line-through?

### ISSUE THREAD

**Issue by r12a** [w3c/typography#7]
**Do not add a comment here, use the following link to make comments visible on the original thread:**
https://github.com/w3c/csswg-drafts/issues/711

**Comment by asmusf** [comment]
I would tentatively say that it doesn't make sense for line through (strikeout). The reason is that it is not so much a decoration as a visible deletion. Deferring to the "ink" makes less logical sense.

For overline, I can imagine scenarios where it might obliterate parts of a character (diacritics), perhaps even a diacritic that is itself a line (macron above some other diacritic). That could alter the sense of the text, so being able to skip the ink would make sense.
